import { Sheet, Student } from "@/types";

export const dummyStudents: Student[] = [
  {
    $id: "s1",
    name: "Ankit Sharma",
    slot: "full_time",
    sheetNumber: 1,
    phone: "+1 (555) 123-4567",
    father_name: "Rakesh Sharma",
    address: "Barna, Phulpur, Prayagraj",
    join_date: new Date().toISOString(),
  },
  {
    $id: "s2",
    name: "Riya Verma",
    slot: "first_half",
    sheetNumber: 2,
    phone: "+1 (555) 987-6543",
    father_name: "Jitesh Verma",
    address: "Latif Pur, Phulpur, Prayagraj",
    join_date: new Date().toISOString(),
  },
  {
    $id: "s3",
    name: "Karan Mehta",
    slot: "last_half",
    sheetNumber: 2,
    father_name: "Shubham Mehta",
    address: "Barna, Phulpur, Prayagraj",
    join_date: new Date().toISOString(),
  },
  {
    $id: "s4",
    name: "Neha Gupta",
    slot: "full_time",
    sheetNumber: 3,
    phone: "+1 (555) 246-8101",
    father_name: "Jitesh Gupta",
    address: "Phulpur, Prayagraj",
    join_date: new Date().toISOString(),
  },
  {
    $id: "s5",
    name: "Amit Singh",
    slot: "first_half",
    sheetNumber: 4,
    father_name: "Rajesh Singh",
    address: "Barna, Phulpur, Prayagraj",
    join_date: new Date().toISOString(),
  },
  {
    $id: "s6",
    name: "Priya Tiwari",
    slot: "last_half",
    sheetNumber: 4,
    phone: "+1 (555) 369-1214",
    father_name: "Shubham Tiwari",
    address: "Latif Pur, Phulpur, Prayagraj",
    join_date: new Date().toISOString(),
  },
  {
    $id: "s7",
    name: "Rohit Yadav",
    slot: "first_half",
    sheetNumber: 5,
    father_name: "Sagar Yadav",
    address: "Barna, Phulpur, Prayagraj",
    join_date: new Date().toISOString(),
  },
  {
    $id: "s8",
    name: "Sneha Chauhan",
    slot: "full_time",
    sheetNumber: 6,
    phone: "+1 (555) 481-6325",
    father_name: "Shubham Chauhan",
    address: "Barna, Phulpur, Prayagraj",
    join_date: new Date().toISOString(),
  },
  {
    $id: "s9",
    name: "Deepak Kumar",
    slot: "last_half",
    sheetNumber: 5,
    phone: "+1 (555) 481-6325",
    father_name: "Dinesh Kumar",
    address: "Barna, Phulpur, Prayagraj",
    join_date: new Date().toISOString(),
  },
  {
    $id: "s10",
    name: "Ayesha Khan",
    slot: "first_half",
    sheetNumber: 7,
    phone: "+1 (555) 481-6325",
    father_name: "Salman Khan",
    address: "Barna, Phulpur, Prayagraj",
    join_date: new Date().toISOString(),
  },
];

export const dummySheets :Sheet[] = [
  { sheetNumber: 1, status: "full" },
  {
    sheetNumber: 2,
    status: "full",
    firstHalfName: "Riya Verma",
    lastHalfName: "Karan Mehta",
  },
  { sheetNumber: 3, status: "full", fullTimeName: "Neha Gupta" },
  {
    sheetNumber: 4,
    status: "full",
    firstHalfName: "Amit Singh",
    lastHalfName: "Priya Tiwari",
  },
  {
    sheetNumber: 5,
    status: "full",
    firstHalfName: "Rohit Yadav",
    lastHalfName: "Deepak Kumar",
  },
  { sheetNumber: 6, status: "full", fullTimeName: "Sneha Chauhan" },
  { sheetNumber: 7, status: "half", firstHalfName: "Ayesha Khan" },
];
