import { Sheet, Student } from "@/types";

export const dummyStudents: Student[] = [
  {
    "$id": "s1",
    name: "Ankit Sharma",
    slot: "full_time",
    sheetNumber: 1,
    phone: '+1 (555) 123-4567',
    father_name: 'Rakesh Sharma',
    address: "Barna, Phulpur, Prayagraj",
    is_active: true,
    join_date: new Date().toISOString(),
  },
  {
    "$id": "s2",
    name: "Riya Verma",
    slot: "first_half",
    sheetNumber: 2,
    phone: "+1 (555) 987-6543",
    father_name: 'Jitesh Verma',
    address: "Latif Pur, Phulpur, Prayagraj",
    is_active: true,
    join_date: new Date().toISOString(),
  },
  {
    "$id": "s3",
    name: "Karan Mehta",
    slot: "last_half",
    sheetNumber: 2,
    father_name: 'Shubham Mehta',
    address: "Barna, Phulpur, Prayagraj",
    is_active: true,
    join_date: new Date().toISOString(),
  },
  {
    "$id": "s4",
    name: "Neha Gupta",
    slot: "full_time",
    sheetNumber: 3,
    phone: "+1 (555) 246-8101",
    father_name: 'Jitesh Gupta',
    address: "Phulpur, Prayagraj",
    is_active: true,
    join_date: new Date().toISOString(),
  },
  {
    "$id": "s5",
    name: "Amit Singh",
    slot: "first_half",
    sheetNumber: 4,
    father_name: 'Rajesh Singh',
    address: "Barna, Phulpur, Prayagraj",
    is_active: true,
    join_date: new Date().toISOString(),
  },
  {
    "$id": "s6",
    name: "Priya Tiwari",
    slot: "last_half",
    sheetNumber: 4,
    phone: "+1 (555) 369-1214",
    father_name: 'Shubham Tiwari',
    address: "Latif Pur, Phulpur, Prayagraj",
    is_active: true,
    join_date: new Date().toISOString(),
  },
  {
    "$id": "s7",
    name: "Rohit Yadav",
    slot: "first_half",
    sheetNumber: 5,
    father_name: 'Sagar Yadav',
    address: "Barna, Phulpur, Prayagraj",
    is_active: true,
    join_date: new Date().toISOString(),
  },
  {
    "$id": "s8",
    name: "Sneha Chauhan",
    slot: "full_time",
    sheetNumber: 6,
    phone: "+1 (555) 481-6325",
    father_name: 'Shubham Chauhan',
    address: "Barna, Phulpur, Prayagraj",
    is_active: true,
    join_date: new Date().toISOString(),
  },
  {
    "$id": "s9",
    name: "Deepak Kumar",
    slot: "last_half",
    sheetNumber: 5,
    phone: "+1 (555) 481-6325",
    father_name: 'Dinesh Kumar',
    address: "Barna, Phulpur, Prayagraj",
    is_active: true,
    join_date: new Date().toISOString(),
  },
  {
    "$id": "s10",
    name: "Ayesha Khan",
    slot: "first_half",
    sheetNumber: 7,
    phone: "+1 (555) 481-6325",
    father_name: 'Salman Khan',
    address: "Barna, Phulpur, Prayagraj",
    is_active: true,
    join_date: new Date().toISOString(),
  },
  {
    "$id": "s101",
    name: "Ravi Sharma",
    slot: "full_time",
    sheetNumber: 8,
    phone: "+91 9876543210",
    father_name: 'Mahesh Sharma',
    address: "Barna, Phulpur, Prayagraj",
    is_active: true,
    join_date: new Date().toISOString(),
  },
  {
    "$id": "s102",
    name: "Meena Joshi",
    slot: "first_half",
    sheetNumber: 9,
    phone: "+91 9123456780",
    father_name: 'Yash Joshi',
    address: "Barna, Phulpur, Prayagraj",
    is_active: true,
    join_date: new Date().toISOString(),
  },
  {
    "$id": "s103",
    name: "Arjun Verma",
    slot: "last_half",
    sheetNumber: 9,
    phone: "+91 9988776655",
    father_name: 'Rakesh Verma',
    address: "Barna, Phulpur, Prayagraj",
    is_active: true,
    join_date: new Date().toISOString(),
  },
  {
    "$id": "s104",
    name: "Sneha Rani",
    slot: "first_half",
    sheetNumber: 10,
    father_name: 'Rajesh Tiwari',
    address: "Barna, Phulpur, Prayagraj",
    is_active: true,
    join_date: new Date().toISOString(),
  },
  {
    "$id": "s105",
    name: "Deepak Yadav",
    slot: "last_half",
    sheetNumber: 10,
    father_name: 'Kuldeep Yadav',
    address: "Barna, Phulpur, Prayagraj",
    is_active: true,
    join_date: new Date().toISOString(),
  },
  {
    "$id": "s106",
    name: "Alok Singh",
    slot: "full_time",
    sheetNumber: 11,
    father_name: 'Shaym Singh',
    address: "Barna, Phulpur, Prayagraj",
    is_active: true,
    join_date: new Date().toISOString(),
  },
  {
    "$id": "s107",
    name: "Nidhi Patel",
    slot: "first_half",
    sheetNumber: 12,
    father_name: 'Shiva Patel',
    address: "Barna, Phulpur, Prayagraj",
    is_active: true,
    join_date: new Date().toISOString(),
  },
  {
    "$id": "s108",
    name: "Anshul Gupta",
    slot: "last_half",
    sheetNumber: 12,
    father_name: 'Arjun Kumar Gupta',
    address: "Barna, Phulpur, Prayagraj",
    is_active: true,
    join_date: new Date().toISOString(),
  },
  {
    "$id": "s109",
    name: "Ritika Jain",
    slot: "full_time",
    sheetNumber: 13,
    father_name: 'Shivam Jain',
    address: "Barna, Phulpur, Prayagraj",
    is_active: true,
    join_date: new Date().toISOString(),
  },
  {
    "$id": "s110",
    name: "Mohit Agarwal",
    slot: "first_half",
    sheetNumber: 14,
    father_name: 'Shobhit Agarwal',
    address: "Barna, Phulpur, Prayagraj",
    is_active: true,
    join_date: new Date().toISOString(),
  },
];

export const dummySheets: Sheet[] = [
  { sheetNumber: 1, status: "full", fullTimeName: "Ankit Sharma" },
  {
    sheetNumber: 2,
    status: "full",
    firstHalfName: "Riya Verma",
    lastHalfName: "Karan Mehta",
  },
  { sheetNumber: 3, status: "full", fullTimeName: "Neha Gupta" },
  {
    sheetNumber: 4,
    status: "full",
    firstHalfName: "Amit Singh",
    lastHalfName: "Priya Tiwari",
  },
  {
    sheetNumber: 5,
    status: "full",
    firstHalfName: "Rohit Yadav",
    lastHalfName: "Deepak Kumar",
  },
  { sheetNumber: 6, status: "full", fullTimeName: "Sneha Chauhan" },
  { sheetNumber: 7, status: "half", firstHalfName: "Ayesha Khan" },
  { sheetNumber: 8, status: "full", fullTimeName: "Ravi Sharma" },
  {
    sheetNumber: 9,
    status: "full",
    firstHalfName: "Meena Joshi",
    lastHalfName: "Arjun Verma",
  },
  {
    sheetNumber: 10,
    status: "full",
    firstHalfName: "Sneha Rani",
    lastHalfName: "Deepak Yadav",
  },
  { sheetNumber: 11, status: "full", fullTimeName: "Alok Singh" },
  {
    sheetNumber: 12,
    status: "full",
    firstHalfName: "Nidhi Patel",
    lastHalfName: "Anshul Gupta",
  },
  { sheetNumber: 13, status: "full", fullTimeName: "Ritika Jain" },
  { sheetNumber: 14, status: "half", firstHalfName: "Mohit Agarwal" },
];
